
project_id = "cmpggiyuiattqjmddcac"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324

[edge-functions]
enabled = true
port = 54323

[functions.retry-razorpay-order]
verify_jwt = true

[functions.download-design]
verify_jwt = true

[functions.create-razorpay-order]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = false

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true

port = 54323
